Manager webpack config
{ name: 'manager',
  mode: 'development',
  bail: false,
  devtool: 'none',
  entry: 
   [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/dist/server/common/polyfills.js',
     '/Users/giulia/Sites/electric_g/ffconf2019/storybook/addons.js',
     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/dist/client/manager/index.js' ],
  output: 
   { path: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/dist/public',
     filename: '[name].[chunkhash].bundle.js',
     publicPath: '' },
  cache: {},
  plugins: 
   [ DllReferencePlugin {
       options: 
        { context: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/node_modules',
          manifest: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/dll/storybook_ui-manifest.json' } },
     HtmlWebpackPlugin {
       options: 
        { template: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/dist/server/templates/index.ejs',
          templateContent: false,
          templateParameters: [Function: templateParameters],
          filename: 'index.html',
          hash: false,
          inject: false,
          compile: true,
          favicon: false,
          minify: undefined,
          cache: true,
          showErrors: true,
          chunks: 'all',
          excludeChunks: [],
          chunksSortMode: 'none',
          meta: {},
          title: 'Webpack App',
          xhtml: false,
          alwaysWriteToDisk: true },
       childCompilerHash: undefined,
       childCompilationOutputName: undefined,
       assetJson: undefined,
       hash: undefined,
       version: 4 },
     CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
     DefinePlugin { definitions: {} },
     DefinePlugin {
       definitions: 
        { 'process.env': { NODE_ENV: '"development"', NODE_PATH: '""', PUBLIC_URL: '""' },
          NODE_ENV: '"development"' } },
     ContextReplacementPlugin {
       resourceRegExp: /graphql-language-service-interface[\/\\]dist/,
       newContentResource: undefined,
       newContentRecursive: undefined,
       newContentRegExp: /\.js$/ },
     NormalModuleReplacementPlugin { resourceRegExp: /core-js/, newResource: [Function] } ],
  module: 
   { rules: 
      [ { test: /\.(mjs|jsx?)$/,
          use: 
           [ { loader: 'babel-loader',
               options: 
                { cacheDirectory: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/.cache/storybook',
                  presets: 
                   [ [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/preset-env/lib/index.js',
                       { shippedProposals: true, useBuiltIns: 'usage', corejs: '3' } ],
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/preset-react/lib/index.js',
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/preset-flow/lib/index.js' ],
                  plugins: 
                   [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js',
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/plugin-proposal-class-properties/lib/index.js',
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js',
                     [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.js',
                       { sourceMap: true, autoLabel: true } ],
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/babel-plugin-macros/dist/index.js',
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/plugin-transform-react-constant-elements/lib/index.js',
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/babel-plugin-add-react-displayname/index.js',
                     [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/babel-plugin-react-docgen/lib/index.js',
                       { DOC_GEN_COLLECTION_NAME: 'STORYBOOK_REACT_CLASSES' } ] ] } } ],
          include: [ '/Users/giulia/Sites/electric_g/ffconf2019' ],
          exclude: [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules' ] },
        { test: /\.css$/,
          use: 
           [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/style-loader/index.js',
             { loader: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/node_modules/css-loader/dist/cjs.js',
               options: { importLoaders: 1 } } ] },
        { test: /\.(svg|ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani)(\?.*)?$/,
          loader: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/file-loader/dist/cjs.js',
          query: { name: 'static/media/[name].[hash:8].[ext]' } },
        { test: /\.(mp4|webm|wav|mp3|m4a|aac|oga)(\?.*)?$/,
          loader: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/url-loader/dist/cjs.js',
          query: { limit: 10000, name: 'static/media/[name].[hash:8].[ext]' } } ] },
  resolve: 
   { extensions: [ '.mjs', '.js', '.jsx', '.json' ],
     modules: [ 'node_modules' ],
     alias: 
      { '@emotion/core': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@emotion/core',
        '@emotion/styled': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@emotion/styled',
        'emotion-theming': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/emotion-theming',
        '@storybook/addons': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/addons',
        '@storybook/api': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/api',
        '@storybook/channels': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/channels',
        '@storybook/components': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/components',
        '@storybook/core-events': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core-events',
        '@storybook/router': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/router',
        '@storybook/theming': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/theming',
        '@storybook/ui': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/ui',
        'prop-types': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/prop-types',
        react: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/react',
        'react-dom': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/react-dom' } },
  recordsPath: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/.cache/storybook/records.json',
  performance: { hints: false },
  optimization: { splitChunks: { chunks: 'all' }, runtimeChunk: true } }
[ HtmlWebpackPlugin {
    options: 
     { template: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/dist/server/templates/index.ejs',
       templateContent: false,
       templateParameters: [Function: templateParameters],
       filename: 'iframe.html',
       hash: false,
       inject: false,
       compile: true,
       favicon: false,
       minify: undefined,
       cache: true,
       showErrors: true,
       chunks: 'all',
       excludeChunks: [],
       chunksSortMode: 'none',
       meta: {},
       title: 'Webpack App',
       xhtml: false,
       alwaysWriteToDisk: true },
    childCompilerHash: undefined,
    childCompilationOutputName: undefined,
    assetJson: undefined,
    hash: undefined,
    version: 4 },
  DefinePlugin {
    definitions: 
     { 'process.env': { NODE_ENV: '"development"', NODE_PATH: '""', PUBLIC_URL: '"."' },
       NODE_ENV: '"development"' } },
  WatchMissingNodeModulesPlugin {
    nodeModulesPath: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules' },
  HotModuleReplacementPlugin {
    options: {},
    multiStep: undefined,
    fullBuildTimeout: 200,
    requestTimeout: 10000 },
  CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
  ProgressPlugin {
    profile: false,
    handler: undefined,
    modulesCount: 500,
    showEntries: false,
    showModules: true,
    showActiveModules: true },
  DefinePlugin { definitions: {} },
  NormalModuleReplacementPlugin { resourceRegExp: /core-js/, newResource: [Function] } ]
Preview webpack config
{ mode: 'development',
  bail: false,
  devtool: '#cheap-module-source-map',
  entry: 
   [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/dist/server/common/polyfills.js',
     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/dist/server/preview/globals.js',
     '/Users/giulia/Sites/electric_g/ffconf2019/storybook/config.js',
     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/webpack-hot-middleware/client.js?reload=true' ],
  output: 
   { path: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/dist/public',
     filename: '[name].[hash].bundle.js',
     publicPath: '' },
  plugins: 
   [ HtmlWebpackPlugin {
       options: 
        { template: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/dist/server/templates/index.ejs',
          templateContent: false,
          templateParameters: [Function: templateParameters],
          filename: 'iframe.html',
          hash: false,
          inject: false,
          compile: true,
          favicon: false,
          minify: undefined,
          cache: true,
          showErrors: true,
          chunks: 'all',
          excludeChunks: [],
          chunksSortMode: 'none',
          meta: {},
          title: 'Webpack App',
          xhtml: false,
          alwaysWriteToDisk: true },
       childCompilerHash: undefined,
       childCompilationOutputName: undefined,
       assetJson: undefined,
       hash: undefined,
       version: 4 },
     DefinePlugin {
       definitions: 
        { 'process.env': { NODE_ENV: '"development"', NODE_PATH: '""', PUBLIC_URL: '"."' },
          NODE_ENV: '"development"' } },
     WatchMissingNodeModulesPlugin {
       nodeModulesPath: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules' },
     HotModuleReplacementPlugin {
       options: {},
       multiStep: undefined,
       fullBuildTimeout: 200,
       requestTimeout: 10000 },
     CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
     ProgressPlugin {
       profile: false,
       handler: undefined,
       modulesCount: 500,
       showEntries: false,
       showModules: true,
       showActiveModules: true },
     DefinePlugin { definitions: {} },
     NormalModuleReplacementPlugin { resourceRegExp: /core-js/, newResource: [Function] } ],
  module: 
   { rules: 
      [ { test: /\.(mjs|jsx?)$/,
          use: 
           [ { loader: 'babel-loader',
               options: 
                { cacheDirectory: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/.cache/storybook',
                  presets: 
                   [ [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/preset-env/lib/index.js',
                       { shippedProposals: true, useBuiltIns: 'usage', corejs: '3' } ],
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/preset-react/lib/index.js',
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/preset-flow/lib/index.js' ],
                  plugins: 
                   [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js',
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/plugin-proposal-class-properties/lib/index.js',
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js',
                     [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.js',
                       { sourceMap: true, autoLabel: true } ],
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/babel-plugin-macros/dist/index.js',
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@babel/plugin-transform-react-constant-elements/lib/index.js',
                     '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/babel-plugin-add-react-displayname/index.js',
                     [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/babel-plugin-react-docgen/lib/index.js',
                       { DOC_GEN_COLLECTION_NAME: 'STORYBOOK_REACT_CLASSES' } ] ] } } ],
          include: [ '/Users/giulia/Sites/electric_g/ffconf2019' ],
          exclude: [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules' ] },
        { test: /\.md$/,
          use: 
           [ { loader: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/node_modules/raw-loader/dist/cjs.js' } ] },
        { test: /\.css$/,
          sideEffects: true,
          use: 
           [ '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/style-loader/index.js',
             { loader: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/node_modules/css-loader/dist/cjs.js',
               options: { importLoaders: 1 } },
             { loader: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/postcss-loader/src/index.js',
               options: { ident: 'postcss', postcss: {}, plugins: [Function: plugins] } } ] },
        { test: /\.(svg|ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani)(\?.*)?$/,
          loader: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/file-loader/dist/cjs.js',
          query: { name: 'static/media/[name].[hash:8].[ext]' } },
        { test: /\.(mp4|webm|wav|mp3|m4a|aac|oga)(\?.*)?$/,
          loader: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/url-loader/dist/cjs.js',
          query: { limit: 10000, name: 'static/media/[name].[hash:8].[ext]' } } ] },
  resolve: 
   { extensions: [ '.mjs', '.js', '.jsx', '.json' ],
     modules: [ 'node_modules' ],
     alias: 
      { 'babel-runtime/core-js/object/assign': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/@storybook/core/node_modules/core-js/es/object/assign.js',
        react: '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/react',
        'react-dom': '/Users/giulia/Sites/electric_g/ffconf2019/node_modules/react-dom' } },
  optimization: 
   { splitChunks: { chunks: 'all' },
     runtimeChunk: true,
     minimizer: 
      [ TerserPlugin {
          options: 
           { test: /\.m?js(\?.*)?$/i,
             chunkFilter: [Function: chunkFilter],
             warningsFilter: [Function: warningsFilter],
             extractComments: false,
             sourceMap: true,
             cache: true,
             cacheKeys: [Function: cacheKeys],
             parallel: true,
             include: undefined,
             exclude: undefined,
             minify: undefined,
             terserOptions: 
              { output: { comments: /^\**!|@preserve|@license|@cc_on/i },
                mangle: false,
                keep_fnames: true } } } ] },
  performance: { hints: false } }